# Travis CI config file

dist: focal # Ubuntu 20.x

language: python

compiler:
  - g++
  #  - clang

python:
  - '3.8'
  #- 3.8-dev
  #- nightly

before_install:
  # HEPMC3 and LHAPDF6
  - cd install && yes y | source autoinstall.sh && source setenv.sh && cd ..

install:
  - pip install -r requirements.txt
  - make -j8 TEST=TRUE

script:
  # Event generation and plots
  - ./bin/gr -i ./input/test.json -h 0 -w true -l false
  - python ./python/iceshot --hepmc3 test

  # Ray tuning
  - ray start --head
  - python ./python/icetune --tuneset fast

  # C++ tests
  - for i in {0,1,2,3}; do "./bin/testbench$i"; done
  
  # Python driven tests (fast mode --> POMLOOP False)
  - pytest tests/testbench_cepdata.py -s --POMLOOP False --NEVENTS 2000
  - pytest tests/testbench_exloop.py -s --POMLOOP False --NEVENTS 2000
  - pytest tests/testbench_vgrid.py -s
  - pytest tests/testbench_integrators.py -s
  - pytest tests/testbench_global_fast.py -s
  - pytest tests/testbench_global_slow.py -s
  
  #- pytest --cov
  #- make -C docs/ clean
  #- make -C docs/ html
  #- touch docs/build/html/.nojekyll

after_success:
  #- coverage run --source=httpsuite -m pytest tests/
  #- coveralls

deploy:
  #  - provider: pypi
  #    user: "__token__"
  #    password: $PYPI_TOKEN
  #    skip_existing: true

  #  - provider: pages:git
  #    verbose: true
  #    token: $GITHUB_TOKEN
  #    edge: true
  #    local_dir: ./docs/build/html/
  #    keep_history: true
