language: python
compiler:
  - g++
python:
#- '3.7'
  - '3.8'
#- 3.8-dev
#- nightly
before_install:
  - cd install && yes y | source autoinstall.sh && source setenv.sh && cd ..
install:
  - pip install -r requirements.txt
  - make -j8
script:
#- pytest --cov
#- make -C docs/ clean
#- make -C docs/ html
#- touch docs/build/html/.nojekyll

after_success:
#- coverage run --source=httpsuite -m pytest tests/
#- coveralls
deploy:
#  - provider: pypi
#    user: "__token__"
#    password: $PYPI_TOKEN
#    skip_existing: true

#  - provider: pages:git
#    verbose: true
#    token: $GITHUB_TOKEN
#    edge: true
#    local_dir: ./docs/build/html/
#    keep_history: true
